# Generated by Django 5.2.7 on 2025-10-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(null=True)),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('_week_day', models.TextField(default='[]')),
                ('routine_type', models.ManyToManyField(blank=True, related_name='types', to='cortana_routine.routinetype')),
            ],
        ),
    ]
