# Generated by Django 5.2.7 on 2025-10-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortana_routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
